app = 'quanta-app'
primary_region = 'lhr'

[build]
dockerfile = "Dockerfile"

[services]
protocol = "tcp"

[http_service]
internal_port = 3000
force_https = false
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
protocol = "http"
timeout = "5s"

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
